In [1]:
from sklearn.datasets import fetch_openml

In [3]:
mnist = fetch_openml('mnist_784', version =1)

In [4]:
X = mnist.data
y = mnist.target

In [5]:
import numpy as np

print(X.shape)
print(y.shape)

(70000, 784)
(70000,)


In [9]:
# 값 중에 유니크한 값들을 보여줌(중복제거)
np.unique(y)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype=object)

In [10]:
# 데이터 타입이 object이므로 int로 바꿔줌
y = y.astype(np.int)

<ipython-input-10-18535e954694>:2: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  y = y.astype(np.int)


In [11]:
np.unique(y)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [13]:
from sklearn.neural_network import MLPClassifier 

mlp = MLPClassifier(learning_rate_init= 0.0001, max_iter=100, activation = 'relu', hidden_layer_sizes=(10,10))
clf = mlp.fit(X_train, y_train)
y_pred = clf.predict(X_test)

C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:619: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


In [14]:
import sklearn.metrics as mt

print('정확도 :',mt.accuracy_score(y_test,y_pred))
print(mt.confusion_matrix(y_test, y_pred))

정확도 : 0.9006190476190477
[[1993    0    2    0    9    4   19    2   47    0]
 [   3 2291   22    5    3   11    3    3   38   11]
 [  13   11 1933   24   14    5   31   17   72    4]
 [  10    9   87 1802    1   69   10   21  137   19]
 [   3    5   13    1 1862    0   34   15   13  117]
 [  72   11    6   72   17 1568   48    5  101   23]
 [  34    0   15    0   22   32 1873    1   21    1]
 [  10    6   11   19   22    2    4 1953   60   69]
 [  36   21   44   17   13   31   23    9 1810   44]
 [   2    7    1    5   52   10    2   67   82 1828]]


In [15]:
# X에 들어있던 데이터는 255이하의 값이므로 255로 나눠주면 정규화가 됨
X = X/255
# 이렇게 하고 다시 돌리면 정확도 향상 가능

In [16]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=1)

In [17]:
from sklearn.neural_network import MLPClassifier 

mlp = MLPClassifier(learning_rate_init= 0.0001, max_iter=100, activation = 'relu', hidden_layer_sizes=(10,10))
clf = mlp.fit(X_train, y_train)
y_pred = clf.predict(X_test)

C:\Users\Administrator\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:614: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (100) reached and the optimization hasn't converged yet.
  warnings.warn(


In [18]:
import sklearn.metrics as mt

print('정확도 :',mt.accuracy_score(y_test,y_pred))
print(mt.confusion_matrix(y_test, y_pred))

정확도 : 0.926952380952381
[[1982    0   16    5    5   13   25    8   18    4]
 [   2 2314   19   24    0    2    1    3   21    4]
 [  16    7 1966   26   19    4   14   23   40    9]
 [  12   15   60 1923    2   60    1   27   44   21]
 [   4   14   15    1 1910    0   18    4   16   81]
 [  14   10    3   55   23 1750   29    3   23   13]
 [  21    2   18    0   12   20 1906    0   16    4]
 [   8   10   16    6   21    2    0 2019    4   70]
 [  15   34   25   35   13   38   12   10 1840   26]
 [   5   11    6   27   69    5    2   65   10 1856]]
